name: random_game

packages:
  - ./**

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  # build runner build
  build_all:
    run: dart pub global run melos exec --depends-on="build_runner" "dart run build_runner build"
    description: build_runner build all modules.

  build_data:
    run: dart pub global run melos exec --fail-fast --scope="*data*" --depends-on="build_runner" "dart run build_runner build"
    description: build_runner build data module.

  build_domain:
    run: dart pub global run melos exec --fail-fast --scope="*domain*" --depends-on="build_runner" "dart run build_runner build"
    description: build_runner build domain module.

  build_app:
    run: dart pub global run melos exec --fail-fast --scope="*app*" --depends-on="build_runner" "dart run build_runner build"
    description: build_runner build app module.

  build_shared:
    run: dart pub global run melos exec --fail-fast --scope="*shared*" --depends-on="build_runner" "flutter packages pub run build_runner build"
    description: build_runner build shared module.

  # build runner watch
  watch_all:
    run: dart pub global run melos exec --depends-on="build_runner" "dart run build_runner watch"
    description: build_runner watch all modules.

  watch_data:
    run: dart pub global run melos exec --fail-fast --scope="*data*" --depends-on="build_runner" "dart run build_runner watch"
    description: build_runner watch data module.

  watch_domain:
    run: dart pub global run melos exec --fail-fast --scope="*domain*" --depends-on="build_runner" "dart run build_runner watch"
    description: build_runner watch domain module.

  watch_app:
    run: dart pub global run melos exec --fail-fast --scope="*app*" --depends-on="build_runner" "dart run build_runner watch"
    description: build_runner watch app module.

  watch_shared:
    run: dart pub global run melos exec --fail-fast --scope="*shared*" --depends-on="build_runner" "flutter packages pub run build_runner watch"
    description: build_runner watch shared module.

  # build runner build --delete-conflicting-outputs
  force_build_all:
    run: dart pub global run melos exec --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
    description: build_runner build all modules.

  force_build_data:
    run: dart pub global run melos exec --fail-fast --scope="*data*" --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
    description: build_runner build data module.

  force_build_domain:
    run: dart pub global run melos exec --fail-fast --scope="*domain*" --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
    description: build_runner build domain module.

  force_build_app:
    run: dart pub global run melos exec --fail-fast --scope="*app*" --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
    description: build_runner build app module.

  force_build_shared:
    run: dart pub global run melos exec --fail-fast --scope="*shared*" --depends-on="build_runner" "flutter packages pub run build_runner build --delete-conflicting-outputs"
    description: build_runner build shared module.

  # build runner watch --delete-conflicting-outputs
  force_watch_all:
    run: dart pub global run melos exec --depends-on="build_runner" "dart run build_runner watch --delete-conflicting-outputs"
    description: build_runner watch all modules.

  force_watch_data:
    run: dart pub global run melos exec --fail-fast --scope="*data*" --depends-on="build_runner" "dart run build_runner watch --delete-conflicting-outputs"
    description: build_runner watch data module.

  force_watch_domain:
    run: dart pub global run melos exec --fail-fast --scope="*domain*" --depends-on="build_runner" "dart run build_runner watch --delete-conflicting-outputs"
    description: build_runner watch domain module.

  force_watch_app:
    run: dart pub global run melos exec --fail-fast --scope="*app*" --depends-on="build_runner" "dart run build_runner watch --delete-conflicting-outputs"
    description: build_runner watch app module.

  force_watch_shared:
    run: dart pub global run melos exec --fail-fast --scope="*shared*" --depends-on="build_runner" "flutter packages pub run build_runner watch --delete-conflicting-outputs"
    description: build_runner watch shared module.

  pub_get_data:
    run: dart pub global run melos exec --fail-fast --scope="*data*" "flutter pub get"
    description: pub get data module.

  pub_get_domain:
    run: dart pub global run melos exec --fail-fast --scope="*domain*" "flutter pub get"
    description: pub get domain module.

  pub_get_app:
    run: dart pub global run melos exec --fail-fast --scope="*app*" "flutter pub get"
    description: pub get app module.

  pub_get_shared:
    run: dart pub global run melos exec --fail-fast --scope="*shared*" "flutter pub get"
    description: pub get shared module.
